/**
 * MasterDocs Export Service
 * Generates high-yield study artifacts:
 * 1. Clean GitHub-Flavored Markdown for Notion / Obsidian
 * 2. Anki Spaced Repetition Decks (.tsv / .txt)
 * 3. Print-Ready PDF Executive Cheat Sheet Trigger
 */

import type { DocPage, SubjectMetadata, SubjectId } from '../types/docs.types';
import { ALL_SUBJECTS_CATALOG, TOPICS_BY_SUBJECT } from '../data/subjectsCatalog';
import { docsProgressService } from './docsProgressService';

export class DocsExportService {
  /**
   * Generates a comprehensive, clean GFM Markdown dossier
   */
  public generateMarkdownDossier(doc: DocPage, subject: SubjectMetadata): string {
    const lines: string[] = [];

    // Header & Frontmatter metadata
    lines.push(`# ${doc.title}`);
    lines.push(`> **Track**: ${subject.title} (${subject.category}) | **Level**: Senior / Staff Engineer`);
    lines.push('');
    lines.push(doc.description);
    lines.push('');
    lines.push('---');
    lines.push('');

    // Overview
    lines.push('## 1. Overview');
    lines.push(doc.overview);
    lines.push('');

    // Why It Matters
    lines.push('## 2. Why It Matters in Senior Interviews');
    lines.push(doc.whyItMatters);
    lines.push('');

    // How It Works Under The Hood
    lines.push('## 3. How It Works (Internals & Spec)');
    lines.push(doc.howItWorks);
    lines.push('');

    // Formal Syntax
    if (doc.syntaxReference) {
      lines.push('## 4. Syntax & API Specification');
      lines.push('```typescript');
      lines.push(doc.syntaxReference);
      lines.push('```');
      lines.push('');
    }

    // Dynamic Sections & Code
    if (doc.sections && doc.sections.length > 0) {
      lines.push('## 5. Architectural Deep Dives');
      doc.sections.forEach((section, idx) => {
        lines.push(`### 5.${idx + 1} ${section.heading}`);
        lines.push(section.content);
        if (section.codeSnippet) {
          lines.push('');
          lines.push(`\`\`\`${section.codeSnippet.language || 'typescript'}`);
          lines.push(section.codeSnippet.code);
          lines.push('```');
        }
        lines.push('');
      });
    }

    // Common Pitfalls
    if (doc.commonMistakes && doc.commonMistakes.length > 0) {
      lines.push('## 6. Common Production Pitfalls & Interview Traps');
      doc.commonMistakes.forEach((mistake) => {
        lines.push(`- ⚠️ **Trap**: ${mistake}`);
      });
      lines.push('');
    }

    // Top Interview Questions & Flashcards
    if (doc.questions && doc.questions.length > 0) {
      lines.push('## 7. FAANG Interview Questions & Strong Senior Answers');
      doc.questions.forEach((q, qIdx) => {
        lines.push(`### Q${qIdx + 1}: ${q.question}`);
        lines.push(`**Difficulty**: \`${q.difficulty.toUpperCase()}\` | **Type**: \`${q.type}\``);
        lines.push('');
        lines.push(`**Executive Answer**:`);
        lines.push(q.shortAnswer);
        lines.push('');
        if (q.detailedAnswer) {
          lines.push('<details><summary><b>Detailed Technical Breakdown</b></summary>');
          lines.push('');
          lines.push(q.detailedAnswer);
          if (q.seniorAnswer) {
            lines.push('');
            lines.push(`**Staff/Principal Signal**: ${q.seniorAnswer}`);
          }
          lines.push('');
          lines.push('</details>');
          lines.push('');
        }
      });
    }

    lines.push('---');
    lines.push(`*Generated by Frontend MasterDocs University (${new Date().toLocaleDateString()})*`);

    return lines.join('\n');
  }

  /**
   * Generates Anki-compatible TSV text format for spaced repetition
   * Format: Front [TAB] Back [TAB] Tags
   */
  public generateAnkiDeck(doc: DocPage, subject: SubjectMetadata): string {
    const lines: string[] = [];

    // Anki Header Directives
    lines.push('#separator:tab');
    lines.push('#html:true');
    lines.push('#tags column:3');

    const cleanTag = (str: string) => str.replace(/[^a-zA-Z0-9_-]/g, '_');
    const baseTags = `${cleanTag(subject.id)} ${cleanTag(doc.topicId)} masterdocs frontend_interview`;

    // 1. Core Concept Card
    const conceptFront = `<b>[${subject.title}]</b> What is <i>${doc.title}</i>, and why is it critical in frontend engineering?`;
    const conceptBack = `<p>${this.escapeHtml(doc.overview)}</p><hr><p><b>Why It Matters:</b> ${this.escapeHtml(doc.whyItMatters)}</p>`;
    lines.push(`${conceptFront}\t${conceptBack}\t${baseTags} core_concept`);

    // 2. How It Works Under The Hood Card
    const internalsFront = `<b>[${subject.title} - Internals]</b> How does <i>${doc.title}</i> work under the hood?`;
    const internalsBack = `<p>${this.escapeHtml(doc.howItWorks)}</p>`;
    lines.push(`${internalsFront}\t${internalsBack}\t${baseTags} internals`);

    // 3. Syntax Card
    if (doc.syntaxReference) {
      const syntaxFront = `<b>[${subject.title} - Syntax]</b> What is the fundamental syntax/signature for <i>${doc.title}</i>?`;
      const syntaxBack = `<pre><code>${this.escapeHtml(doc.syntaxReference)}</code></pre>`;
      lines.push(`${syntaxFront}\t${syntaxBack}\t${baseTags} syntax`);
    }

    // 4. Common Pitfalls Card
    if (doc.commonMistakes && doc.commonMistakes.length > 0) {
      const pitfallsFront = `<b>[${subject.title} - Traps]</b> What are the common production pitfalls when working with <i>${doc.title}</i>?`;
      const pitfallsBack = `<ul>${doc.commonMistakes.map((m) => `<li>⚠️ ${this.escapeHtml(m)}</li>`).join('')}</ul>`;
      lines.push(`${pitfallsFront}\t${pitfallsBack}\t${baseTags} pitfalls`);
    }

    // 5. Interview Questions Cards
    if (doc.questions && doc.questions.length > 0) {
      doc.questions.forEach((q) => {
        const qFront = `<b>[Interview: ${q.difficulty.toUpperCase()}]</b> ${this.escapeHtml(q.question)}`;
        let qBack = `<p><b>Short Answer:</b> ${this.escapeHtml(q.shortAnswer)}</p>`;
        if (q.detailedAnswer) {
          qBack += `<hr><p><b>In-Depth:</b> ${this.escapeHtml(q.detailedAnswer)}</p>`;
        }
        if (q.seniorAnswer) {
          qBack += `<p><b>Senior/Staff Signal:</b> ${this.escapeHtml(q.seniorAnswer)}</p>`;
        }
        lines.push(`${qFront}\t${qBack}\t${baseTags} ${cleanTag(q.difficulty)} interview_q`);
      });
    }

    return lines.join('\n');
  }

  /**
   * Initiates browser download of a generated text/markdown file
   */
  public downloadFile(filename: string, content: string, mimeType: string): void {
    if (typeof window === 'undefined') return;

    const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Copies formatted text directly to user clipboard
   */
  public async copyToClipboard(text: string): Promise<boolean> {
    if (typeof navigator === 'undefined' || !navigator.clipboard) {
      return false;
    }
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Invokes native window print dialog configured for executive cheat sheet PDF
   */
  public triggerPrint(): void {
    if (typeof window !== 'undefined') {
      window.print();
    }
  }

  public triggerPrintView(): void {
    this.triggerPrint();
  }

  public exportMarkdownStudyPlan(): void {
    const progress = docsProgressService.getProgress();
    const stats = docsProgressService.getSyllabusStats();
    const lines: string[] = [];
    lines.push('# Frontend MasterDocs - Candidate Personalized Study Plan');
    lines.push(`> Generated on ${new Date().toLocaleDateString()} | Overall Completion: ${stats.completionPercentage}%`);
    lines.push('');
    lines.push('## Progress Overview');
    lines.push(`- **Topics Completed**: ${stats.totalCompletedTopics} / ${stats.totalSyllabusTopics}`);
    lines.push(`- **Bookmarked Topics**: ${progress.bookmarkedDocs.length}`);
    lines.push(`- **Bookmarked Questions**: ${progress.bookmarkedQuestions.length}`);
    lines.push(`- **Questions Mastered**: ${Object.values(progress.questionMastery).filter(m => m === 'mastered').length}`);
    lines.push('');
    lines.push('## 21 Curriculum Tracks Breakdown');
    ALL_SUBJECTS_CATALOG.forEach(s => {
      const topics = TOPICS_BY_SUBJECT[s.id] || [];
      const completedCount = topics.filter(t => docsProgressService.isTopicCompleted(s.id, t.id)).length;
      const percent = topics.length > 0 ? Math.round((completedCount / topics.length) * 100) : 0;
      lines.push(`### ${s.icon} ${s.title} (${percent}% - ${completedCount}/${topics.length})`);
      topics.forEach(t => {
        const isDone = docsProgressService.isTopicCompleted(s.id, t.id) ? 'x' : ' ';
        const isBookmarked = docsProgressService.isDocBookmarked(s.id, t.id) ? ' ⭐' : '';
        lines.push(`- [${isDone}] ${t.title}${isBookmarked}`);
      });
      lines.push('');
    });
    this.downloadFile('masterdocs-study-plan.md', lines.join('\n'), 'text/markdown');
  }

  public exportTrackCheatSheet(subjectId: SubjectId): void {
    const subject = ALL_SUBJECTS_CATALOG.find(s => s.id === subjectId);
    if (!subject) return;
    const topics = TOPICS_BY_SUBJECT[subjectId] || [];
    const lines: string[] = [];
    lines.push(`# ${subject.icon} ${subject.title} - Complete Executive Cheat Sheet`);
    lines.push(`> Category: ${subject.category} | ${topics.length} Key Curriculum Topics`);
    lines.push('');
    lines.push(subject.description);
    lines.push('');
    lines.push('## Core Competency Checklist');
    topics.forEach((t, i) => {
      lines.push(`### ${i + 1}. ${t.title}`);
      lines.push(t.description);
      if (t.subtopics && t.subtopics.length > 0) {
        lines.push('**Subtopics:**');
        t.subtopics.forEach(st => {
          lines.push(`- ${st.title}`);
        });
      }
      lines.push('');
    });
    this.downloadFile(`${subjectId}-track-cheat-sheet.md`, lines.join('\n'), 'text/markdown');
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/\n/g, '<br>');
  }
}

export const docsExportService = new DocsExportService();
