// scripts/generators/standardAngles.mjs
// 8 Orthogonal Interview Lenses guaranteeing distinct question titles and difficulty tiers

export function getStandardAngles(subjectName) {
  return [
    {
      lensName: 'Fresher Fundamentals',
      difficulty: 'EASY',
      experienceLevel: 'FRESHER',
      questionType: 'DEFINITION',
      title: (t) => `What is ${t.name}, and what is its primary role in ${subjectName}?`,
      shortAnswer: (t) => `${t.name} is a fundamental concept in ${subjectName} used for ${t.purpose}. It provides predictable behavior, readability, and structural integrity.`,
      interviewAnswer: (t) => `When asked about ${t.name} in an interview, I explain: 1) Its core definition and role in ${subjectName}. 2) Why developers use it rather than alternative approaches. 3) A clear, concrete example demonstrating proper syntax.`,
      detailedExplanation: (t) => `### Core Overview of ${t.name}\n\n1. **Definition**: ${t.name} represents ${t.purpose}.\n2. **Importance**: Without ${t.name}, developers encounter maintainability issues, syntax errors, or unexpected runtime behavior.\n3. **Application**: Used across all modern web development setups to establish clean, reliable code.`,
      why: (t) => `${t.name} was established in ${subjectName} to provide a standardized, deterministic approach to ${t.purpose}.`,
      howItWorks: (t) => `1. The ${subjectName} environment parses and registers ${t.name}.\n2. Standard evaluation rules apply to bind properties, state, or elements.\n3. The result is committed to memory or the browser render pipeline.`,
      realWorldExample: (t) => `In production applications, correctly utilizing ${t.name} ensures fast development cycles, fewer bugs, and full compliance with industry standards.`,
    },
    {
      lensName: 'Syntax & Implementation',
      difficulty: 'EASY',
      experienceLevel: 'FRESHER',
      questionType: 'CODE',
      title: (t) => `How do you correctly declare and use ${t.name} in practical ${subjectName} code?`,
      shortAnswer: (t) => `To implement ${t.name}, write standard ${subjectName} syntax following official specifications, ensuring proper parameters and clean formatting.`,
      interviewAnswer: (t) => `I demonstrate ${t.name} by writing clean, readable code with proper formatting, appropriate options/attributes, and clear variable naming.`,
      detailedExplanation: (t) => `### Practical Implementation of ${t.name}\n\n- **Syntax Requirements**: Adheres strictly to modern ${subjectName} conventions.\n- **Readability**: Keeps code self-documenting for team members.\n- **Error Prevention**: Avoids legacy anti-patterns and unhandled edge cases.`,
      why: (t) => `Standardized syntax for ${t.name} guarantees cross-platform compatibility and simplifies automated linting and testing.`,
      howItWorks: (t) => `1. Source code is ingested and tokenized.\n2. The compiler/engine verifies syntax validity for ${t.name}.\n3. Execution proceeds according to runtime specifications.`,
      realWorldExample: (t) => `Every day in production codebases, developers write ${t.name} following linted style guides to keep the codebase maintainable.`,
    },
    {
      lensName: 'Nuances & Comparisons',
      difficulty: 'EASY',
      experienceLevel: '1_3_YEARS',
      questionType: 'CONCEPTUAL',
      title: (t) => `What are the key differences between ${t.name} and related alternatives in ${subjectName}?`,
      shortAnswer: (t) => `${t.name} differs from alternative techniques primarily in syntax conciseness, performance characteristics, and scope of application.`,
      interviewAnswer: (t) => `In interviews, comparing ${t.name} with alternatives shows conceptual depth. I contrast syntax overhead, runtime trade-offs, and typical use cases.`,
      detailedExplanation: (t) => `### Comparative Analysis: ${t.name}\n\n- **Direct Alternative**: Older or competing constructs in ${subjectName}.\n- **Advantages**: More expressive, less boilerplate, better developer ergonomics.\n- **When to choose which**: Choose ${t.name} for modern standard workflows.`,
      why: (t) => `Understanding differences helps engineers make informed architectural choices rather than blindly copying patterns.`,
      howItWorks: (t) => `1. Comparing AST representations shows differences in instruction sets.\n2. Memory and execution steps vary based on the chosen pattern.\n3. Modern engines optimize ${t.name} with specialized JIT/pipeline heuristics.`,
      realWorldExample: (t) => `Migrating legacy constructs to ${t.name} reduced boilerplate by 30% and eliminated subtle regressions during client onboarding.`,
    },
    {
      lensName: 'Common Mistakes & Debugging',
      difficulty: 'INTERMEDIATE',
      experienceLevel: '1_3_YEARS',
      questionType: 'DEBUGGING',
      title: (t) => `What are the most frequent beginner mistakes and bugs encountered with ${t.name}?`,
      shortAnswer: (t) => `Frequent mistakes with ${t.name} stem from misunderstanding its scope, omitting necessary configurations, and improper lifecycle handling.`,
      interviewAnswer: (t) => `During code reviews, common issues with ${t.name} include incorrect assumptions about mutability, missing null checks, or incorrect binding.`,
      detailedExplanation: (t) => `### Debugging & Common Mistakes in ${t.name}\n\n1. **Misconception**: Assuming ${t.name} behaves like a different construct.\n2. **Detection**: Identifying subtle issues through unit tests and browser DevTools.\n3. **Resolution**: Applying idiomatic defensive coding patterns.`,
      why: (t) => `Mastering the failure modes of ${t.name} prevents production outages and lowers mean time to resolution (MTTR).`,
      howItWorks: (t) => `1. Flawed code triggers runtime warnings or invalid states.\n2. Defensive guards or validation intercept errors before state corruption.\n3. Correct implementation restores deterministic behavior.`,
      realWorldExample: (t) => `Catching a silent failure in ${t.name} during pre-commit linting prevented a critical regression from reaching production users.`,
    },
    {
      lensName: 'Engine Internals & Evaluation',
      difficulty: 'INTERMEDIATE',
      experienceLevel: '3_5_YEARS',
      questionType: 'OUTPUT',
      title: (t) => `How does the browser or runtime engine process and evaluate ${t.name} under the hood?`,
      shortAnswer: (t) => `Under the hood, the runtime engine tokenizes ${t.name}, parses it into an AST or internal data structure, and executes it via optimized bytecode or render pipelines.`,
      interviewAnswer: (t) => `I explain the internal lifecycle of ${t.name}: 1) Parsing and tokenization. 2) Memory allocation and scope/render registration. 3) Execution and garbage collection/cleanup.`,
      detailedExplanation: (t) => `### Internal Mechanics of ${t.name}\n\n- **Compilation/Parsing Phase**: AST generation and static validation.\n- **Execution Phase**: Runtime bytecode evaluation or DOM/CSSOM tree updates.\n- **Optimization**: Hot-path inline caching and layout tree batching.`,
      why: (t) => `Knowledge of runtime internals enables developers to write performant code that aligns with engine optimizations rather than fighting them.`,
      howItWorks: (t) => `1. Bytecode compiler generates intermediate representations.\n2. JIT compiler or layout engine processes instructions.\n3. Execution completes in microsecond timelines with minimal memory allocations.`,
      realWorldExample: (t) => `Understanding how the engine optimizes ${t.name} allowed our team to achieve a 60 FPS animation target on low-end Android mobile devices.`,
    },
    {
      lensName: 'Interview Traps & Quirks',
      difficulty: 'INTERMEDIATE',
      experienceLevel: '3_5_YEARS',
      questionType: 'SCENARIO',
      title: (t) => `Interview Trap: What subtle edge cases or trick scenarios surround ${t.name}?`,
      shortAnswer: (t) => `The trickiest aspect of ${t.name} involves coercion, asynchronous timing, or unexpected fallback behaviors under non-standard conditions.`,
      interviewAnswer: (t) => `Interviewers often ask edge-case questions about ${t.name} to check if candidates truly understand the specification or just memorized high-level syntax.`,
      detailedExplanation: (t) => `### Deconstructing Interview Traps for ${t.name}\n\n- **The Trap**: What looks intuitive on the surface produces counter-intuitive results.\n- **The Root Cause**: Underlying specification rules and implicit conversions.\n- **How to Answer**: State the specification rationale and provide the exact output.`,
      why: (t) => `Edge cases test depth of knowledge and indicate an engineer capable of debugging high-severity esoteric bugs in production.`,
      howItWorks: (t) => `1. Edge input arrives at the boundary of ${t.name}.\n2. Engine falls back to specification fallback algorithms.\n3. Result reflects the exact W3C / ECMA standard specification.`,
      realWorldExample: (t) => `An unexpected edge case in ${t.name} caused intermittent test flakiness until an explicit defensive guard was introduced.`,
    },
    {
      lensName: 'Performance & Optimization',
      difficulty: 'DIFFICULT',
      experienceLevel: '5_8_YEARS',
      questionType: 'PERFORMANCE',
      title: (t) => `What are the performance implications, memory footprint, and optimization techniques for ${t.name}?`,
      shortAnswer: (t) => `Performance with ${t.name} depends on avoiding excessive allocations, preventing layout thrashing or unneeded re-renders, and enabling cache reuse.`,
      interviewAnswer: (t) => `In high-scale systems, I optimize ${t.name} by profiling CPU and memory with DevTools, minimizing object churn, and batching heavy operations.`,
      detailedExplanation: (t) => `### High-Performance ${t.name} Engineering\n\n- **Resource Cost**: Computational complexity and allocation overhead.\n- **Optimization Levers**: Memoization, lazy evaluation, and off-main-thread processing.\n- **Benchmarking**: Validating throughput with Chrome Performance profiler and Lighthouse.`,
      why: (t) => `At scale, unoptimized usage of ${t.name} aggregates into sluggish user interactions, frame drops, and battery drain.`,
      howItWorks: (t) => `1. Bottleneck identification using flame graphs.\n2. Refactoring ${t.name} to minimize synchronous work.\n3. Engine skips redundant passes, lowering CPU utilization.`,
      realWorldExample: (t) => `Refactoring ${t.name} across our feed list reduced peak heap memory by 45MB and improved interaction latency by 35ms.`,
    },
    {
      lensName: 'Production Architecture',
      difficulty: 'DIFFICULT',
      experienceLevel: '8_PLUS_YEARS',
      questionType: 'ARCHITECTURE',
      title: (t) => `Enterprise Architecture: How should ${t.name} be structured for large-scale production applications?`,
      shortAnswer: (t) => `In enterprise systems, ${t.name} must be encapsulated behind clean abstractions, guarded by automated testing, and monitored with observability metrics.`,
      interviewAnswer: (t) => `For production architectures serving millions of users, I treat ${t.name} as a first-class citizen: enforced via ESLint rules, covered by unit/integration tests, and tracked via real user monitoring (RUM).`,
      detailedExplanation: (t) => `### Enterprise System Design for ${t.name}\n\n- **Modularity & Contracts**: Decoupling ${t.name} behind clear interfaces.\n- **Resilience**: Graceful degradation and circuit breakers.\n- **Scalability**: Ensuring zero-regression deployments across multi-team codebases.`,
      why: (t) => `Large enterprises require predictable patterns so hundreds of engineers can contribute safely without degrading the core system.`,
      howItWorks: (t) => `1. Architectural boundaries isolate ${t.name}.\n2. CI/CD pipelines run automated audits.\n3. Production telemetries monitor health in real time.`,
      realWorldExample: (t) => `Standardizing ${t.name} within our core platform package cut cross-team onboarding time by half and achieved 99.99% frontend uptime.`,
    },
  ];
}
