export { default as PlacementApp } from './PlacementApp'
export * from './types/placement.types'
export { PLACEMENT_PROGRAM, PLACEMENT_DAYS, PLACEMENT_TOPICS, PLACEMENT_DAY_DEFINITIONS, DEFAULT_DAILY_WORKLOAD } from './data/curriculum'
export { PLACEMENT_QUESTIONS, getVerifiedQuestions, pickQuestions, buildDailyPracticePlan, buildWeaknessPracticeSet } from './data/questions'
export { PLACEMENT_DSA_PATTERNS, PLACEMENT_DSA_PROBLEM_COUNT } from './data/dsaPatterns'
export { placementService } from './services/placement.service'
export { placementReadinessService, DEFAULT_READINESS_CONFIG } from './services/placementReadiness.service'
export { placementApplicationsService } from './services/placementApplications.service'
export { placementMentorService } from './services/placementMentor.service'
export { usePlacement } from './hooks/usePlacement'
export { usePlacementReadiness } from './hooks/usePlacementReadiness'
