// scripts/dom-gen/part1.cjs
// Questions 1 to 100: DOM Basics, Element Selection, and DOM Traversal

const questions = [
  // --- DOM Basics & Architecture (1 - 30) ---
  {
    topic: "DOM Basics & Architecture",
    subtopic: "DOM Definition",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the Document Object Model (DOM) in web development?",
    shortAnswer: "The DOM is a standardized tree-like representation of an HTML or XML document that enables programming languages like JavaScript to inspect and modify document structure, content, and styling dynamically.",
    detailedExplanation: "- **Object Tree**: The browser parses HTML text into an interconnected hierarchy of JavaScript node objects.\n- **Programming Interface**: Exposes standardized APIs to create, select, modify, or delete elements at runtime.\n- **Standardized**: Governed by the WHATWG DOM Living Standard, ensuring identical behavior across modern browsers.",
    codeExample: "// Accessing document node and updating page title dynamically:\nconsole.log(document.nodeType); // 9 (DOCUMENT_NODE)\ndocument.title = 'Updated Dashboard';",
    interviewTips: ["Clarify that the DOM is not the raw HTML text file, but an in-memory object graph parsed from it."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "HTML vs DOM",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the primary difference between raw HTML source code and the live DOM?",
    shortAnswer: "HTML is static source text sent from a server, while the DOM is the active in-memory object tree constructed by the browser parser that JavaScript inspects and mutates.",
    detailedExplanation: "- **Static Source vs Live Tree**: HTML is an inert string; the DOM is an active hierarchy of JavaScript objects.\n- **Error Correction**: Browser parsers automatically fix malformed HTML (e.g., adding missing `<tbody>` tags).\n- **Runtime Mutations**: JavaScript alters the live DOM in memory without modifying the original HTML file on the server.",
    codeExample: "// HTML source: <table><tr><td>Sample</td></tr></table>\n// Live DOM automatically inserts a <tbody> element:\nconst table = document.querySelector('table');\nconsole.log(table.firstElementChild.tagName); // 'TBODY'",
    interviewTips: ["Mention parser error-correction (e.g. inserting `<tbody>`) as a concrete proof that DOM differs from HTML."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Window vs Document",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between window and document in browser JavaScript?",
    shortAnswer: "`window` represents the browser tab and global JavaScript execution context, while `document` is a property of `window` representing the loaded HTML document.",
    detailedExplanation: "- **`window`**: Global execution object owning timers (`setTimeout`), storage, navigation (`location`), and viewport sizes.\n- **`document`**: The root entry point to the DOM tree (`window.document`) containing elements and query methods.\n- **Relationship**: `document` is a child property of `window` (`window.document === document`).",
    codeExample: "console.log(window.document === document); // true\nconsole.log(window.innerWidth);           // Viewport width\nconsole.log(document.body.clientWidth);   // Body content width",
    interviewTips: ["State that `window` provides the execution environment, while `document` provides the content hierarchy."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Node vs Element",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between a Node and an Element in the DOM tree?",
    shortAnswer: "A Node is any point in the tree (including text, comments, and document), while an Element is specifically a Node of type 1 (ELEMENT_NODE) representing an HTML tag.",
    detailedExplanation: "- **`Node`**: The generic base class. Types include Element (1), Text (3), Comment (8), and Document (9).\n- **`Element`**: Subclass of Node. Contains HTML tag attributes, classList, innerHTML, and CSS styling.\n- **Collection Difference**: `childNodes` returns all child Nodes; `children` returns only Element nodes.",
    codeExample: "const div = document.createElement('div');\ndiv.innerHTML = 'Hello <!-- comment --> World';\n\nconsole.log(div.childNodes.length); // 3 (Text, Comment, Text)\nconsole.log(div.children.length);   // 0 (No Element children)",
    interviewTips: ["Use `childNodes` vs `children` to cleanly demonstrate the distinction in code."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "nodeType Property",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What are the common numeric nodeType values returned by DOM nodes?",
    shortAnswer: "Common values are `1` for Element, `3` for Text node, `8` for Comment node, `9` for Document, and `11` for DocumentFragment.",
    detailedExplanation: "- **`Node.ELEMENT_NODE` (1)**: HTML element tags like `<div>` or `<p>`.\n- **`Node.TEXT_NODE` (3)**: Text content within elements, including whitespace.\n- **`Node.COMMENT_NODE` (8)**: Comment annotations (`<!-- ... -->`).\n- **`Node.DOCUMENT_NODE` (9)**: The root `document` object.\n- **`Node.DOCUMENT_FRAGMENT_NODE` (11)**: Lightweight in-memory document container.",
    codeExample: "function printType(node) {\n  if (node.nodeType === Node.ELEMENT_NODE) console.log('Element:', node.tagName);\n  if (node.nodeType === Node.TEXT_NODE) console.log('Text content:', node.nodeValue.trim());\n}",
    interviewTips: ["Remember that 1 is Element and 3 is Text — these are the two most frequently tested types."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Root Element",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How do you access the root <html> element of a document in the DOM?",
    shortAnswer: "Access `document.documentElement`, which returns the top-level `<html>` Element node of the document.",
    detailedExplanation: "- **Root Element**: `document.documentElement` references the `<html>` element.\n- **CSS `:root` Equivalent**: CSS `:root` corresponds directly to `document.documentElement` in HTML.\n- **Contrast with `document`**: `document` is the Document node (type 9); `document.documentElement` is the Element node (type 1).",
    codeExample: "console.log(document.documentElement.tagName); // 'HTML'\nconsole.log(document.documentElement.parentNode === document); // true",
    interviewTips: ["Differentiate between the `document` root node and `document.documentElement` which is the `<html>` element."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "document.body Timing",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "Why might document.body return null when called in an external JavaScript file?",
    shortAnswer: "`document.body` returns `null` if the script executes synchronously inside the `<head>` before the browser parser reaches and creates the `<body>` tag.",
    detailedExplanation: "- **Parsing Order**: The browser parses HTML top to bottom. In `<head>`, `<body>` has not been parsed yet.\n- **Resolution 1**: Add the `defer` attribute to the `<script>` tag so it runs after HTML parsing finishes.\n- **Resolution 2**: Move the `<script>` tag to the bottom of `<body>` right before `</body>`.\n- **Resolution 3**: Listen for the `DOMContentLoaded` event before accessing `document.body`.",
    codeExample: "// Inside <head> without defer:\nconsole.log(document.body); // null\n\n// Safe approach:\ndocument.addEventListener('DOMContentLoaded', () => {\n  console.log(document.body.tagName); // 'BODY'\n});",
    interviewTips: ["This is a classic rookie bug explanation: synchronous `<head>` scripts execute before `<body>` exists."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Ready States",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What are the three values of document.readyState and what do they indicate?",
    shortAnswer: "`document.readyState` returns `'loading'`, `'interactive'`, or `'complete'`, tracking the document's parsing and subresource download status.",
    detailedExplanation: "- **`'loading'`**: The document is currently loading and HTML parsing is in progress.\n- **`'interactive'`**: The document has finished parsing and the DOM tree is built, but external assets (images) are still downloading.\n- **`'complete'`**: The document and all external resources (images, stylesheets) have finished loading.\n- **Event**: The `readystatechange` event fires whenever this property changes.",
    codeExample: "document.addEventListener('readystatechange', () => {\n  console.log('Ready state changed to:', document.readyState);\n});\n\nif (document.readyState === 'complete') {\n  console.log('Page is already fully loaded.');\n}",
    interviewTips: ["Note that `interactive` corresponds to `DOMContentLoaded`, while `complete` corresponds to `window.load`."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "DOMContentLoaded Event",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the DOMContentLoaded event and why is it preferred over window.onload for UI setup?",
    shortAnswer: "`DOMContentLoaded` fires as soon as the HTML DOM tree is fully parsed without waiting for stylesheets and images, allowing interactive UI logic to initialize much faster.",
    detailedExplanation: "- **`DOMContentLoaded`**: Fired on `document`. UI controls, click handlers, and DOM lookups can initialize immediately.\n- **`window.onload`**: Fired on `window`. Waits for megabytes of images, stylesheets, and iframes to finish downloading.\n- **Performance**: Prevents user-facing interaction delays on slow network connections.",
    codeExample: "document.addEventListener('DOMContentLoaded', () => {\n  document.querySelector('#start-btn').addEventListener('click', startGame);\n});",
    interviewTips: ["Explain that waiting for `window.onload` frustrates users when large images take seconds to download."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Script Attributes",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How do the defer and async attributes change script execution in relation to the DOM?",
    shortAnswer: "`defer` downloads scripts in parallel and runs them in order after HTML parsing completes, while `async` executes scripts immediately upon download, interrupting HTML parsing.",
    detailedExplanation: "- **`<script>` (Default)**: Blocks HTML parsing while downloading and executing.\n- **`<script defer>`**: Downloads asynchronously; executes in document order right before `DOMContentLoaded`.\n- **`<script async>`**: Downloads asynchronously; executes as soon as ready with no order guarantee, pausing parsing.\n- **Recommendation**: Use `defer` for scripts that interact with the DOM or depend on other scripts.",
    codeExample: "<!-- Runs in order after DOM parsing: -->\n<script defer src=\"bundle.js\"></script>\n\n<!-- Runs whenever downloaded: -->\n<script async src=\"analytics.js\"></script>",
    interviewTips: ["Summary: `defer` guarantees order and DOM readiness; `async` has no order guarantee."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Document Title",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How do you read and update the document title programmatically in JavaScript?",
    shortAnswer: "Read or assign to `document.title`, which sets the text displayed in the browser tab and bookmark label.",
    detailedExplanation: "- **Getter**: Reads the inner text content of the `<title>` tag inside `<head>`.\n- **Setter**: Mutating `document.title = 'New Title'` updates the tab title immediately without page reload.\n- **Single Page Apps**: Essential for reflecting current view context and maintaining accessibility in client-side routers.",
    codeExample: "console.log('Current title:', document.title);\ndocument.title = 'Settings | My Application';",
    interviewTips: ["Highlight its importance in SPAs for updating the tab title during client-side navigation."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Document URL",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between document.URL and window.location.href?",
    shortAnswer: "`document.URL` is a read-only string returning the document's URL, whereas `window.location.href` is read-write and can trigger navigation when reassigned.",
    detailedExplanation: "- **`document.URL`**: Static read-only string property on `Document`.\n- **`window.location.href`**: Property of the `Location` object. Assigning a new URL navigates the browser.\n- **Navigation API**: `window.location` provides methods like `.replace()` and `.reload()`, while `document.URL` has no methods.",
    codeExample: "console.log(document.URL); // Read-only URL string\n\n// Reassigning location.href navigates the page:\n// window.location.href = 'https://example.com';",
    interviewTips: ["Remember: `document.URL` cannot be assigned to navigate; assign to `location.href` instead."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Document Referrer",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does document.referrer return and when is it an empty string?",
    shortAnswer: "`document.referrer` returns the URL of the page that linked to the current page, or an empty string if navigated directly, via bookmarks, or blocked by Referrer-Policy.",
    detailedExplanation: "- **Origin Tracking**: Identifies the referring page URL for internal analytics.\n- **Empty Scenarios**: Direct URL bar entry, bookmark clicks, HTTPS-to-HTTP transitions, or `Referrer-Policy: no-referrer`.\n- **Read-Only**: Stored as a read-only string property on `document`.",
    codeExample: "if (document.referrer) {\n  console.log('Referred from:', document.referrer);\n} else {\n  console.log('Direct navigation or referrer suppressed.');\n}",
    interviewTips: ["Mention how modern browser Referrer-Policy headers can strip referrer strings for privacy."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Document Cookies",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How does document.cookie work and what cookies are hidden from it?",
    shortAnswer: "`document.cookie` reads and writes semicolon-delimited cookie strings, but cookies configured with the `HttpOnly` flag cannot be accessed by JavaScript.",
    detailedExplanation: "- **Getter**: Returns all accessible non-HttpOnly cookies formatted as `'name1=value1; name2=value2'`.\n- **Setter**: Assigning `document.cookie = 'theme=dark; path=/; max-age=3600'` appends or updates a single cookie.\n- **Security**: The `HttpOnly` flag prevents JavaScript from reading session cookies, neutralizing cookie theft via XSS.",
    codeExample: "// Writing a cookie:\ndocument.cookie = 'theme=dark; path=/; max-age=86400; SameSite=Lax';\n\n// Reading cookies:\nconsole.log(document.cookie);",
    interviewTips: ["Emphasize that sensitive session tokens should always have `HttpOnly` enabled on the server."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Character Encoding",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How do you check the active character encoding of the document in the DOM?",
    shortAnswer: "Inspect `document.characterSet`, which returns the canonical character encoding name (such as `'UTF-8'`).",
    detailedExplanation: "- **Property**: `document.characterSet` is a read-only string property.\n- **Origin**: Determined by HTTP Content-Type headers or the `<meta charset=\"UTF-8\">` tag.\n- **Historical**: Supersedes legacy non-standard aliases like `document.charset`.",
    codeExample: "console.log('Encoding:', document.characterSet); // 'UTF-8'",
    interviewTips: ["UTF-8 is the universal standard character encoding for modern web applications."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Document Head & Body",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What are document.head and document.body shortcuts in the DOM?",
    shortAnswer: "They are direct references to the `<head>` and `<body>` Element nodes of the current document.",
    detailedExplanation: "- **Direct Access**: Avoids the performance overhead of `document.querySelector('body')`.\n- **Null Caveat**: `document.body` evaluates to `null` if queried inside `<head>` before the body parses.\n- **Pairing**: `document.documentElement` gives `<html>`, `document.head` gives `<head>`, and `document.body` gives `<body>`.",
    codeExample: "const headTag = document.head;\nconst bodyTag = document.body;\nconsole.log(headTag.tagName); // 'HEAD'\nconsole.log(bodyTag.tagName); // 'BODY'",
    interviewTips: ["Remind interviewers that `document.body` is `null` if queried inside `<head>` synchronously."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Built-in Collections",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What built-in live collections exist on the document object?",
    shortAnswer: "Built-in live collections include `document.forms`, `document.images`, `document.links`, and `document.scripts`.",
    detailedExplanation: "- **`document.forms`**: Live `HTMLCollection` of all `<form>` elements.\n- **`document.images`**: Live `HTMLCollection` of all `<img>` elements.\n- **`document.links`**: Live `HTMLCollection` of all `<a>` and `<area>` elements having an `href` attribute.\n- **`document.scripts`**: Live `HTMLCollection` of all `<script>` elements.",
    codeExample: "console.log('Total forms on page:', document.forms.length);\nconsole.log('Total images on page:', document.images.length);\nconst firstForm = document.forms[0];",
    interviewTips: ["Mention that these collections update automatically when elements are added or removed from the DOM."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "currentScript Property",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is document.currentScript and why does it return null inside ES modules?",
    shortAnswer: "`document.currentScript` returns the `<script>` element whose script is currently running, but returns `null` inside ES modules because modules execute deferred and asynchronously.",
    detailedExplanation: "- **Classic Scripts**: Returns the executing `<script>` tag. Useful for scripts reading their own configuration `data-*` attributes.\n- **ES Modules**: In `<script type=\"module\">`, `currentScript` is always `null`. Use `import.meta.url` instead.\n- **Callbacks**: Returns `null` if called inside asynchronous callbacks like `setTimeout` or event handlers.",
    codeExample: "// Inside a classic external script:\nconst scriptTag = document.currentScript;\nif (scriptTag) {\n  const apiKey = scriptTag.dataset.apiKey;\n  console.log('API Key:', apiKey);\n}",
    interviewTips: ["State that `document.currentScript` is `null` inside ES modules, where `import.meta.url` must be used instead."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "nodeValue Property",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "What does nodeValue return when called on an element node versus a text node?",
    shortAnswer: "`nodeValue` returns `null` for element nodes, but returns the raw string content for text nodes and comments.",
    detailedExplanation: "- **Element Nodes**: Calling `element.nodeValue` always returns `null` because elements contain child nodes, not direct text values.\n- **Text Nodes**: Returns the editable text string stored in that specific text node.\n- **Comment Nodes**: Returns the comment text string.",
    codeExample: "const p = document.createElement('p');\np.textContent = 'Hello';\nconsole.log(p.nodeValue);           // null (Element)\nconsole.log(p.firstChild.nodeValue); // 'Hello' (Text node)",
    interviewTips: ["This is a classic tricky trivia question: `nodeValue` on an element node is always `null`."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "nodeName vs tagName",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "What is the difference between nodeName and tagName in the DOM?",
    shortAnswer: "`tagName` exists only on Element nodes and returns the tag name in uppercase, while `nodeName` exists on all Node types (returning uppercase tag names for elements, and strings like '#text' for others).",
    detailedExplanation: "- **`tagName`**: Defined on `Element`. Returns tag name in uppercase (e.g. `'DIV'`). Undefined on text or comment nodes.\n- **`nodeName`**: Defined on `Node`. Returns uppercase tag name for elements, `'#text'` for text nodes, and `'#comment'` for comments.\n- **Inheritance**: `Element` inherits `nodeName` from `Node`.",
    codeExample: "const div = document.createElement('div');\nconst text = document.createTextNode('Sample');\n\nconsole.log(div.tagName);   // 'DIV'\nconsole.log(div.nodeName);  // 'DIV'\nconsole.log(text.tagName);  // undefined\nconsole.log(text.nodeName); // '#text'",
    interviewTips: ["State that `tagName` is element-specific, while `nodeName` is universal across all node types."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "hasChildNodes Method",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "How do you check if a DOM node has any child nodes?",
    shortAnswer: "Call `node.hasChildNodes()`, which returns `true` if the node contains any children (including text nodes or comments), or check `node.childNodes.length > 0`.",
    detailedExplanation: "- **`node.hasChildNodes()`**: Fast boolean check for children.\n- **Includes Whitespace**: Returns `true` even if the only child is a whitespace text node.\n- **Element Children Only**: To check for element children specifically, check `node.childElementCount > 0` or `node.children.length > 0`.",
    codeExample: "const el = document.createElement('div');\nconsole.log(el.hasChildNodes()); // false\n\nel.textContent = ' ';\nconsole.log(el.hasChildNodes());       // true (text node child)\nconsole.log(el.childElementCount > 0); // false (no element children)",
    interviewTips: ["Contrast `hasChildNodes()` (any node) with `childElementCount > 0` (element nodes only)."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "DocumentFragment Basics",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "What is a DocumentFragment and why is it used for batch DOM operations?",
    shortAnswer: "A `DocumentFragment` is an off-screen, lightweight container with no parent node that holds DOM nodes and inserts them into the document with a single browser reflow.",
    detailedExplanation: "- **Off-Screen Memory**: Changes inside a fragment do not trigger page reflows or repaints.\n- **Auto-Emptying**: Appending a fragment to the DOM transfers all its child nodes, leaving the fragment empty.\n- **Performance**: Dramatically speeds up appending hundreds of list items compared to appending one-by-one.",
    codeExample: "const frag = document.createDocumentFragment();\nfor (let i = 0; i < 50; i++) {\n  const li = document.createElement('li');\n  li.textContent = `Item ${i}`;\n  frag.appendChild(li);\n}\ndocument.querySelector('ul').appendChild(frag); // 1 single reflow!",
    interviewTips: ["Highlight that appending a fragment automatically empties it and transfers its child nodes."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "element.remove()",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "How do you remove an element from the DOM using modern JavaScript?",
    shortAnswer: "Call `element.remove()`, which detaches the element from its parent in the DOM tree.",
    detailedExplanation: "- **Direct Method**: `element.remove()` can be called directly on the element without referencing its parent.\n- **Legacy Equivalent**: Previously required `element.parentNode.removeChild(element)`.\n- **Memory**: The element remains accessible in JavaScript memory if a variable reference to it is preserved.",
    codeExample: "const toast = document.querySelector('.toast');\nif (toast) {\n  toast.remove(); // Removed from DOM\n}",
    interviewTips: ["Contrast modern `element.remove()` with legacy `element.parentNode.removeChild(element)`."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "cloneNode Method",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "What does cloneNode() do and what does the deep boolean parameter control?",
    shortAnswer: "`cloneNode(deep)` creates a copy of a node. Passing `true` deep-clones all descendant nodes, while `false` (default) copies only the element and its attributes.",
    detailedExplanation: "- **`cloneNode(false)` (Shallow)**: Copies only the tag and attributes; ignores inner text and children.\n- **`cloneNode(true)` (Deep)**: Recursively duplicates the element and all nested children.\n- **No Event Listeners**: Does NOT copy event listeners attached via `addEventListener()`.\n- **ID Duplication**: Always remember to update `id` attributes on cloned nodes to avoid duplicate IDs.",
    codeExample: "const card = document.querySelector('.card');\nconst clone = card.cloneNode(true); // Deep clone\nclone.id = 'card-copy';\ndocument.body.appendChild(clone);",
    interviewTips: ["Always mention that `cloneNode` does NOT duplicate event listeners added via `addEventListener`."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "HTML Template Element",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "What is the HTML <template> element and how do you access its content in the DOM?",
    shortAnswer: "The `<template>` tag holds inert HTML markup that is not rendered on page load, whose contents are accessed as a `DocumentFragment` via `template.content`.",
    detailedExplanation: "- **Inert Markup**: Scripts inside do not execute, styles do not apply, and images do not download until instantiated.\n- **`template.content`**: Returns a `DocumentFragment` holding the parsed template nodes.\n- **Cloning**: Use `document.importNode(template.content, true)` or `template.content.cloneNode(true)` to instantiate copies.",
    codeExample: "const tpl = document.querySelector('#row-template');\nconst clone = tpl.content.cloneNode(true);\nclone.querySelector('.name').textContent = 'Alice';\ndocument.querySelector('tbody').appendChild(clone);",
    interviewTips: ["Explain that `<template>` is parsed into a real DocumentFragment without rendering or downloading resources."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Prototype Chain",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "Explain the prototype inheritance chain of an HTMLButtonElement.",
    shortAnswer: "An `HTMLButtonElement` inherits from `HTMLElement` -> `Element` -> `Node` -> `EventTarget` -> `Object`.",
    detailedExplanation: "- **`EventTarget`**: Base interface providing `addEventListener()`, `removeEventListener()`, and `dispatchEvent()`.\n- **`Node`**: Tree structure interface providing `parentNode`, `childNodes`, and `appendChild()`.\n- **`Element`**: Element interface providing attributes, `classList`, and `querySelector()`.\n- **`HTMLElement`**: HTML layer providing `style`, `dataset`, `tabIndex`, and `click()`.\n- **`HTMLButtonElement`**: Specialized button interface providing `disabled`, `form`, and `type`.",
    codeExample: "const btn = document.createElement('button');\nconsole.log(btn instanceof HTMLButtonElement); // true\nconsole.log(btn instanceof HTMLElement);       // true\nconsole.log(btn instanceof Element);           // true\nconsole.log(btn instanceof Node);              // true\nconsole.log(btn instanceof EventTarget);       // true",
    interviewTips: ["Tracing back to `EventTarget` explains why all DOM elements can listen to and dispatch events."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Live Collections Mutation Trap",
    difficulty: "INTERMEDIATE",
    questionType: "CODE",
    question: "What bug occurs when removing elements while iterating over a live HTMLCollection with a forward for loop?",
    shortAnswer: "Because `HTMLCollection` updates live, removing an element shifts subsequent elements down one index, causing the loop to skip every other element.",
    detailedExplanation: "- **Live Index Shifting**: When index 0 is removed, index 1 becomes index 0. The next iteration inspects index 1, skipping the new index 0.\n- **Solution 1 (Reverse Loop)**: Iterate backwards from `length - 1` down to 0.\n- **Solution 2 (While Loop)**: Continuously remove `collection[0]` while `collection.length > 0`.\n- **Solution 3 (Static Array)**: Copy to a static array using `Array.from()` before looping.",
    codeExample: "// Buggy forward loop with live collection:\nconst items = document.getElementsByClassName('item');\n// for (let i = 0; i < items.length; i++) items[i].remove(); // Skips items!\n\n// Solution: Iterate backwards\nfor (let i = items.length - 1; i >= 0; i--) {\n  items[i].remove();\n}",
    interviewTips: ["This is a classic coding interview trap: live collection mutation requires reverse iteration or array copying."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "DocumentType Node",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "What is document.doctype in the DOM and what does it represent?",
    shortAnswer: "`document.doctype` returns the `DocumentType` node of the document, representing the `<!DOCTYPE html>` declaration.",
    detailedExplanation: "- **Node Type 10**: Represents `Node.DOCUMENT_TYPE_NODE` (value 10).\n- **Properties**: `name` returns `'html'`, `publicId` and `systemId` return DTD identifiers (empty in HTML5).\n- **Rendering Mode**: Tells the browser engine to render in Standard Mode rather than Quirks Mode.",
    codeExample: "console.log(document.doctype.name);     // 'html'\nconsole.log(document.doctype.nodeType); // 10",
    interviewTips: ["Mention that doctype presence ensures the browser operates in Standard Mode instead of Quirks Mode."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "Quirks Mode vs Standards Mode",
    difficulty: "DIFFICULT",
    questionType: "CONCEPTUAL",
    question: "How does Quirks Mode alter CSS box model calculations compared to Standards Mode in the DOM?",
    shortAnswer: "In Quirks Mode, the browser emulates legacy Internet Explorer 5.5 behavior where width and height include padding and borders, unlike Standards Mode where width applies solely to the content box.",
    detailedExplanation: "- **`document.compatMode`**: Returns `'BackCompat'` for Quirks Mode and `'CSS1Compat'` for Standards Mode.\n- **Box Sizing**: Standards Mode uses `box-sizing: content-box` by default; Quirks Mode incorporates borders and padding into specified dimensions.\n- **Inline Element Dimensions**: Quirks Mode incorrectly permits setting width and height on certain inline elements.",
    codeExample: "if (document.compatMode === 'BackCompat') {\n  console.warn('Page is in Quirks Mode! Layout calculations may be distorted.');\n}",
    interviewTips: ["State that `<!DOCTYPE html>` triggers Standards Mode, preventing legacy box-model calculation discrepancies."]
  },
  {
    topic: "DOM Basics & Architecture",
    subtopic: "DOMParser API",
    difficulty: "DIFFICULT",
    questionType: "CODE",
    question: "How does DOMParser safely parse HTML strings without executing inline <script> tags or onerror handlers?",
    shortAnswer: "`DOMParser` parses markup into a detached Document with scripting disabled by default, meaning `<script>` tags and inline event handlers (`<img onerror=...>`) are not executed.",
    detailedExplanation: "- **Detached Context**: Parses into an inert document context disconnected from the active window.\n- **Script Execution Flag**: Browsers set the scripting flag to disabled during `DOMParser` execution.\n- **Security Precaution**: If nodes from the parsed document are subsequently inserted into the live active DOM via `innerHTML` or `appendChild`, some payloads may trigger unless sanitized.",
    codeExample: "const parser = new DOMParser();\nconst doc = parser.parseFromString('<img src=\"x\" onerror=\"alert(1)\">', 'text/html');\n// The alert does NOT fire during DOMParser execution!\nconsole.log(doc.body.firstChild.tagName); // 'IMG'",
    interviewTips: ["Explain that DOMParser disables the scripting flag during parsing, preventing immediate execution."]
  },

  // --- Element Selection & Collections (31 - 70) ---
  {
    topic: "Element Selection & Collections",
    subtopic: "getElementById",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How does document.getElementById() work and what does it return if no element matches?",
    shortAnswer: "`document.getElementById('id')` searches the document for an element matching the specified ID and returns the `Element` object, or `null` if no match exists.",
    detailedExplanation: "- **Fastest Query**: Highly optimized by browser engines using internal ID hash lookup tables.\n- **No Hash Symbol**: Pass the raw ID name without `#`: `getElementById('user')`, not `getElementById('#user')`.\n- **Uniqueness**: If multiple elements share the same ID (invalid HTML), it returns only the first matching element.\n- **Return Value**: Returns an `Element` or `null`.",
    codeExample: "const btn = document.getElementById('submit-btn');\nif (btn) {\n  btn.disabled = true;\n} else {\n  console.warn('Button not found in DOM.');\n}",
    interviewTips: ["State that `getElementById` is the fastest DOM selection method because browsers index IDs internally."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "querySelector",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does document.querySelector() do and what does it return if no element matches?",
    shortAnswer: "`document.querySelector(selector)` returns the first `Element` matching the specified CSS selector string, or `null` if no matching elements are found.",
    detailedExplanation: "- **First Match Only**: Evaluates selectors using standard CSS syntax and returns only the first matching element in document order.\n- **Any CSS Selector**: Supports tag names (`'div'`), classes (`'.active'`), IDs (`'#main'`), attributes (`'[type=\"text\"]'`), and complex combinations (`'ul > li:first-child'`).\n- **Subtree Scoping**: Can be called on any element (`parentElement.querySelector('.child')`) to restrict search to that subtree.",
    codeExample: "const activeItem = document.querySelector('.nav-list > li.active');\nif (activeItem) {\n  console.log('Active item text:', activeItem.textContent);\n}",
    interviewTips: ["Highlight that `querySelector` returns only the first matched element, whereas `querySelectorAll` returns all matches."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "querySelectorAll",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does document.querySelectorAll() return?",
    shortAnswer: "`document.querySelectorAll(selector)` returns a static (non-live) `NodeList` containing all element nodes matching the specified CSS selector in document tree order.",
    detailedExplanation: "- **Static Collection**: The returned `NodeList` is a snapshot. If elements matching the selector are later added or removed from the DOM, the NodeList does not update.\n- **Empty Result**: If no elements match, it returns an empty `NodeList` with `.length === 0` (never `null`).\n- **Built-in `forEach`**: Modern browsers provide a native `.forEach()` method directly on NodeList.",
    codeExample: "const buttons = document.querySelectorAll('button.action-btn');\nconsole.log(`Found ${buttons.length} buttons.`);\n\nbuttons.forEach(btn => {\n  btn.classList.add('ready');\n});",
    interviewTips: ["Emphasize that `querySelectorAll` returns a static snapshot, unlike `getElementsByClassName` which is live."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "getElementsByClassName",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How does getElementsByClassName() differ from querySelectorAll()?",
    shortAnswer: "`getElementsByClassName` returns a live `HTMLCollection` that automatically updates when elements are added or removed, whereas `querySelectorAll` returns a static `NodeList` snapshot.",
    detailedExplanation: "- **Live vs Static**: `HTMLCollection` reflects DOM changes dynamically; static `NodeList` remains frozen at the moment of query.\n- **Method Arguments**: `getElementsByClassName('alert')` takes raw class names without dots; `querySelectorAll('.alert')` accepts complete CSS selector strings.\n- **Iteration**: `NodeList` has built-in `.forEach()`; `HTMLCollection` does not have `.forEach()` and must be converted to an array or looped with a standard `for` loop.",
    codeExample: "// HTMLCollection updates dynamically:\nconst liveList = document.getElementsByClassName('item');\nconsole.log(liveList.length); // 2\n\nconst newItem = document.createElement('div');\nnewItem.className = 'item';\ndocument.body.appendChild(newItem);\n\nconsole.log(liveList.length); // 3 (Live update!)",
    interviewTips: ["Contrast live updating vs static snapshots when comparing `getElementsByClassName` with `querySelectorAll`."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "getElementsByTagName",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does document.getElementsByTagName() return and how do you select all elements in the document?",
    shortAnswer: "It returns a live `HTMLCollection` of elements with the given tag name; passing `'*'` (`document.getElementsByTagName('*')`) returns all elements in the entire document.",
    detailedExplanation: "- **Tag Name Matching**: `document.getElementsByTagName('p')` selects all paragraph elements.\n- **Case Insensitive**: In HTML documents, matching is case-insensitive.\n- **Wildcard Selection**: `document.getElementsByTagName('*')` returns an `HTMLCollection` containing every single element in document order.",
    codeExample: "const paragraphs = document.getElementsByTagName('p');\nconsole.log(`Total paragraphs: ${paragraphs.length}`);\n\n// All elements on the page:\nconst allElements = document.getElementsByTagName('*');\nconsole.log(`Total elements: ${allElements.length}`);",
    interviewTips: ["Mention that `getElementsByTagName('*')` returns all element nodes in the DOM tree."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "getElementsByName",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does document.getElementsByName() do and when is it primarily used?",
    shortAnswer: "`document.getElementsByName('name')` returns a live `NodeList` of elements matching the specified `name` attribute, primarily used for grouping radio buttons and form inputs.",
    detailedExplanation: "- **Target Attribute**: Targets elements with a matching `name=\"...\"` attribute.\n- **Primary Use Case**: Radio button groups that share identical `name` values.\n- **Return Type**: Returns a `NodeList` of elements.\n- **Document-Only**: Defined on `document`, not individual element subtrees.",
    codeExample: "// Getting all radio options for a question:\nconst genderRadios = document.getElementsByName('gender');\ngenderRadios.forEach(radio => {\n  if (radio.checked) console.log('Selected:', radio.value);\n});",
    interviewTips: ["Highlight radio button groups as the primary real-world use case for `getElementsByName`."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "NodeList vs HTMLCollection",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between a NodeList and an HTMLCollection in the DOM?",
    shortAnswer: "An `HTMLCollection` contains only element nodes and is always live, while a `NodeList` can contain any node type (including text nodes) and is typically static when created by `querySelectorAll`.",
    detailedExplanation: "- **Content**: `HTMLCollection` only holds Element nodes; `NodeList` can hold text, comment, and element nodes.\n- **Liveness**: `HTMLCollection` is always live; `NodeList` is static from `querySelectorAll` (though live when returned by `childNodes`).\n- **Methods**: `NodeList` supports `.forEach()`, `entries()`, `keys()`, and `values()`; `HTMLCollection` offers item index access and `.namedItem()`.",
    codeExample: "const collection = document.getElementsByTagName('div'); // HTMLCollection\nconst nodeList = document.querySelectorAll('div');         // NodeList\n\nconsole.log(typeof nodeList.forEach === 'function');    // true\nconsole.log(typeof collection.forEach === 'function');  // false (in standard HTMLCollection)",
    interviewTips: ["Point out that `NodeList` has `.forEach()`, whereas `HTMLCollection` does not."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Converting Collections",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you convert a NodeList or HTMLCollection into a standard JavaScript array?",
    shortAnswer: "Use `Array.from(collection)` or the spread operator `[...collection]` to convert array-like DOM collections into standard JavaScript arrays.",
    detailedExplanation: "- **`Array.from(collection)`**: Converts any array-like or iterable object into a true JavaScript Array instance.\n- **Spread Operator `[...collection]`**: Modern ES6 syntax that spreads iterable DOM nodes into a new array.\n- **Benefits**: Enables standard array methods like `.map()`, `.filter()`, `.reduce()`, and `.find()`.",
    codeExample: "const divElements = document.getElementsByTagName('div');\n\n// Method 1: Spread operator\nconst divArray1 = [...divElements];\n\n// Method 2: Array.from\nconst divArray2 = Array.from(divElements);\n\n// Now you can use map and filter:\nconst ids = divArray1.map(el => el.id);",
    interviewTips: ["Recommend `Array.from` or `[...items]` for unlocking `.filter()` and `.map()` on DOM collections."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Iterating NodeLists",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you loop through all elements selected by document.querySelectorAll()?",
    shortAnswer: "Loop through them using the built-in `NodeList.prototype.forEach()` method or a standard `for...of` loop.",
    detailedExplanation: "- **`NodeList.prototype.forEach()`**: Built directly into all modern browser NodeList implementations.\n- **`for...of` Loop**: Supports `break` and `continue` statements to exit loops early.\n- **Spread to Array**: Spread to an array if you need `.filter()` or `.map()` chaining.",
    codeExample: "const items = document.querySelectorAll('.todo-item');\n\n// Approach 1: forEach\nitems.forEach((item, index) => {\n  item.textContent = `${index + 1}. ${item.textContent}`;\n});\n\n// Approach 2: for...of (allows early break)\nfor (const item of items) {\n  if (item.classList.contains('active')) break;\n}",
    interviewTips: ["Mention that `for...of` is ideal when you need to `break` out of a DOM loop early."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Subtree Selection",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "Can querySelector and querySelectorAll be called on an element instead of document?",
    shortAnswer: "Yes, calling `element.querySelector(selector)` scopes the search exclusively to descendant elements within that specific element's DOM subtree.",
    detailedExplanation: "- **Scoped Query**: `container.querySelectorAll('.item')` searches only descendants of `container`.\n- **Performance**: Dramatically faster than searching the entire document tree for large pages.\n- **Self-Exclusion**: The element itself is never returned, only its descendants matching the selector.",
    codeExample: "const card = document.querySelector('#profile-card');\n// Queries only inside #profile-card:\nconst avatar = card.querySelector('.avatar-img');\nconst bio = card.querySelector('.bio-text');",
    interviewTips: ["Explain that scoping queries to a container element improves query performance significantly."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Attribute Selectors",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you select elements by attribute name and value using querySelector?",
    shortAnswer: "Use CSS attribute selector brackets `[attribute=\"value\"]` inside `querySelector` or `querySelectorAll`.",
    detailedExplanation: "- **Exact Match**: `[name=\"email\"]` matches elements with that exact attribute value.\n- **Attribute Presence**: `[disabled]` matches any element having the attribute regardless of value.\n- **Prefix Match**: `[href^=\"https\"]` matches values starting with 'https'.\n- **Substring Match**: `[class*=\"active\"]` matches values containing 'active'.",
    codeExample: "// Selecting submit buttons:\nconst submitBtn = document.querySelector('button[type=\"submit\"]');\n\n// Selecting all external links:\nconst externalLinks = document.querySelectorAll('a[href^=\"https://\"]');",
    interviewTips: ["Explain prefix (`^=`), suffix (`$=`), and substring (`*=`) attribute matching in CSS queries."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "matches Method",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does the element.matches() method do in the DOM?",
    shortAnswer: "`element.matches(selector)` checks whether an element would be selected by the given CSS selector string, returning `true` or `false`.",
    detailedExplanation: "- **Boolean Test**: Tests an existing element against a CSS selector without performing a DOM search.\n- **Event Delegation**: Heavily used inside delegated event handlers to check if `event.target.matches('.item-button')`.\n- **Syntax**: `element.matches('div.card.active')`.",
    codeExample: "const el = document.querySelector('#button-1');\n\nif (el.matches('button[disabled]')) {\n  console.log('Button is disabled');\n}\n\nif (el.matches('.primary, .btn-action')) {\n  console.log('Element matches primary button styles');\n}",
    interviewTips: ["Highlight `matches()` as the foundational check used in event delegation handlers."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "closest Method",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does the element.closest() method do in the DOM?",
    shortAnswer: "`element.closest(selector)` traverses up the DOM tree starting from the element itself, returning the closest ancestor matching the selector, or `null` if none match.",
    detailedExplanation: "- **Starts at Self**: Evaluates the element itself first; if it matches, it returns the element immediately.\n- **Ascending Traversal**: Moves upward through parent elements until a match is found or document root is reached.\n- **Event Delegation**: Essential for finding parent rows, cards, or forms when a child icon or text inside a button is clicked.",
    codeExample: "document.addEventListener('click', (event) => {\n  // Finds the nearest enclosing table row even if an inner icon was clicked:\n  const row = event.target.closest('tr');\n  if (row) {\n    console.log('Row ID:', row.dataset.id);\n  }\n});",
    interviewTips: ["Differentiate `closest()` (checks self then ancestors) from `parentElement` (direct parent only)."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Empty Query Results",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does querySelector return versus querySelectorAll when no matching elements exist?",
    shortAnswer: "`querySelector()` returns `null`, while `querySelectorAll()` returns an empty `NodeList` with a `length` of 0.",
    detailedExplanation: "- **`querySelector`**: Returns a single `Element` object or `null`. Calling methods on it without a null check throws a `TypeError`.\n- **`querySelectorAll`**: Always returns a valid `NodeList` object. If no items match, `nodeList.length` is 0.\n- **Safe Iteration**: Iterating over `querySelectorAll` with `.forEach()` is safe even when 0 matches exist, as it simply executes zero times.",
    codeExample: "const item = document.querySelector('.non-existent');\nconsole.log(item); // null\n\nconst items = document.querySelectorAll('.non-existent');\nconsole.log(items.length); // 0\nitems.forEach(el => console.log(el)); // Safe: does nothing",
    interviewTips: ["Remind candidates that calling methods on `querySelector` without a null check causes 'Cannot read properties of null'."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Escaping Special Characters",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you select an element whose ID contains dots or colons using querySelector?",
    shortAnswer: "Escape the special characters using `CSS.escape()` or double backslashes in the selector string.",
    detailedExplanation: "- **CSS Syntax Conflict**: `.` denotes a class and `:` denotes a pseudo-class, which breaks raw selector string parsing for IDs like `user:name`.\n- **`CSS.escape()`**: Official standard method that sanitizes arbitrary strings for CSS selector queries.\n- **Manual Escaping**: `document.querySelector('#user\\\\:name')`.",
    codeExample: "const id = 'user:settings.profile';\nconst el = document.querySelector('#' + CSS.escape(id));\nconsole.log(el.textContent);",
    interviewTips: ["Recommend `CSS.escape(id)` as the robust modern API for escaping dynamic IDs."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Multiple Selectors",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you select multiple element types in a single querySelectorAll call?",
    shortAnswer: "Combine selector expressions with commas: `document.querySelectorAll('input, select, textarea')`.",
    detailedExplanation: "- **Comma Combinator**: Evaluates each comma-separated selector branch independently.\n- **Document Order**: Elements matching any branch are returned in document order in a single `NodeList`.\n- **Duplicates Avoided**: An element matching multiple comma branches is included only once.",
    codeExample: "const formControls = document.querySelectorAll('input, select, textarea');\nformControls.forEach(ctrl => ctrl.classList.add('form-input'));",
    interviewTips: ["Mention that elements are returned in document tree order, without duplicates."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Selecting Checked Inputs",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you select all checked radio buttons or checkboxes using querySelectorAll?",
    shortAnswer: "Use the `:checked` pseudo-class: `document.querySelectorAll('input[type=\"checkbox\"]:checked')`.",
    detailedExplanation: "- **Live State**: Selects elements that are currently checked by the user.\n- **Radio and Checkboxes**: Works identically on checkbox inputs, radio buttons, and select `<option>` tags.\n- **Array Mapping**: Combine with `Array.from()` to extract chosen values.",
    codeExample: "const checkedBoxes = document.querySelectorAll('input[name=\"topics\"]:checked');\nconst selected = Array.from(checkedBoxes).map(cb => cb.value);\nconsole.log('Selected topics:', selected);",
    interviewTips: ["Explain that `:checked` tracks the live interactive user state, not just initial HTML attributes."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Selecting Disabled Controls",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you select all disabled form elements using querySelectorAll?",
    shortAnswer: "Use the `:disabled` pseudo-class: `document.querySelectorAll('button:disabled, input:disabled')`.",
    detailedExplanation: "- **`:disabled`**: Matches elements currently in a disabled state.\n- **`:enabled`**: The complementary pseudo-class matching interactive elements.\n- **State Sync**: Matches elements disabled via HTML attribute or via `.disabled = true` in JavaScript.",
    codeExample: "const disabledControls = document.querySelectorAll(':disabled');\ndisabledControls.forEach(ctrl => console.log('Disabled:', ctrl.name || ctrl.id));",
    interviewTips: ["State that `:disabled` reflects both HTML markup and programmatic property changes."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "First and Last Child Selectors",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you select the first and last child of a list container using querySelector?",
    shortAnswer: "Use `:first-child` and `:last-child`: `container.querySelector('li:first-child')` and `container.querySelector('li:last-child')`.",
    detailedExplanation: "- **`:first-child`**: Matches if the element is the very first child of its parent.\n- **`:last-child`**: Matches if the element is the very last child of its parent.\n- **`:first-of-type`**: Contrast with `:first-of-type`, which ignores non-matching sibling tags.",
    codeExample: "const firstItem = document.querySelector('ul.menu > li:first-child');\nconst lastItem = document.querySelector('ul.menu > li:last-child');",
    interviewTips: ["Clarify that `:first-child` fails if another element type precedes it; use `:first-of-type` if siblings vary."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Direct vs Descendant Selectors",
    difficulty: "EASY",
    questionType: "CODE",
    question: "What is the difference between 'ul li' and 'ul > li' in querySelector?",
    shortAnswer: "`ul li` selects all `li` elements at any nesting depth inside `ul`, while `ul > li` selects only direct child `li` elements of the `ul`.",
    detailedExplanation: "- **Descendant Combinator (Space)**: Matches children, grandchildren, and deeply nested submenus.\n- **Child Combinator (`>`)**: Restricts matching exclusively to elements whose immediate parent is `ul`.\n- **Use Case**: `ul > li` is essential for multi-level navigation dropdowns to avoid styling sub-menus prematurely.",
    codeExample: "<!-- <ul id=\"main\"><li>Top <ol><li>Nested</li></ol></li></ul> -->\nconsole.log(document.querySelectorAll('#main > li').length); // 1\nconsole.log(document.querySelectorAll('#main li').length);   // 2",
    interviewTips: ["Highlight preventing unintended styling of nested dropdown menus using `>`."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Selecting by Data Attribute",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How do you query elements having a specific data attribute with querySelector?",
    shortAnswer: "Use attribute selector brackets: `document.querySelectorAll('[data-role=\"dialog\"]')` or `document.querySelectorAll('[data-id]')`.",
    detailedExplanation: "- **Presence vs Value**: `[data-active]` matches presence; `[data-role=\"admin\"]` matches exact value.\n- **Decoupling**: Decouples JavaScript selectors from CSS visual classes, preventing style refactoring bugs.\n- **Dataset Access**: Once queried, access values via `element.dataset.role`.",
    codeExample: "const triggers = document.querySelectorAll('[data-action=\"toggle\"]');\ntriggers.forEach(t => console.log('Target panel:', t.dataset.target));",
    interviewTips: ["Advocate data-attribute selectors to cleanly separate behavioral JS hooks from styling CSS."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Adjacent Sibling Selector",
    difficulty: "EASY",
    questionType: "CODE",
    question: "How does the adjacent sibling combinator '+' work in querySelector?",
    shortAnswer: "`elementA + elementB` matches `elementB` only if it immediately follows `elementA` as a direct sibling under the same parent.",
    detailedExplanation: "- **Immediate Follower**: `elementB` must be positioned directly after `elementA` in the DOM tree.\n- **Shared Parent**: Both elements must share the exact same direct parent node.\n- **General Sibling (`~`)**: In contrast, `~` matches any subsequent sibling, even if not immediately adjacent.",
    codeExample: "const leadParagraph = document.querySelector('h1 + p');\nif (leadParagraph) leadParagraph.classList.add('lead');",
    interviewTips: ["Contrast `+` (immediately adjacent) with `~` (any subsequent sibling)."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: ":is() and :where() Selectors",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "How do :is() and :where() pseudo-class selectors work in querySelector?",
    shortAnswer: "Both group multiple selectors into a single argument, but `:is()` takes the specificity of its most specific argument, while `:where()` always has zero specificity.",
    detailedExplanation: "- **Grouping**: Simplifies writing repetitive selector combinations.\n- **Specificity**: `:is()` assumes highest argument specificity; `:where()` is always `0`.\n- **Forgiving Parsing**: Unrecognized selectors in the list are ignored without invalidating the query.",
    codeExample: "const links = document.querySelectorAll(':is(header, main, footer) a.link');\nconst zeroSpec = document.querySelectorAll(':where(header, main, footer) a.link');",
    interviewTips: ["State that `:is()` adopts the highest specificity, while `:where()` is always zero."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: ":has() Selector",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "How does the :has() relational pseudo-class selector work in querySelector?",
    shortAnswer: "`:has()` acts as a parent/ancestor selector, matching an element if any selector passed into `:has()` matches relative to that element.",
    detailedExplanation: "- **Parent Selector**: Selects a parent based on child state: `article:has(img)` selects articles containing images.\n- **Sibling Combinators**: `h2:has(+ p.lead)` matches an `h2` immediately followed by a lead paragraph.\n- **Modern Milestone**: Solves the decades-old CSS limitation of selecting parents based on children.",
    codeExample: "const cardsWithActiveCheckboxes = document.querySelectorAll('.card:has(input:checked)');\ncardsWithActiveCheckboxes.forEach(c => c.classList.add('selected'));",
    interviewTips: ["Highlight `:has()` as the official solution to the 'parent selector' problem in the DOM."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: ":not() Selector",
    difficulty: "INTERMEDIATE",
    questionType: "CODE",
    question: "How do you select all buttons that do NOT have the .btn-primary class using querySelectorAll?",
    shortAnswer: "Use the `:not()` negation pseudo-class: `document.querySelectorAll('button:not(.btn-primary)')`.",
    detailedExplanation: "- **Negation Filter**: Filters out elements matching the selector inside parentheses.\n- **Multiple Arguments**: Modern CSS allows comma-separated arguments: `button:not(.primary, .secondary)`.\n- **Chaining**: Can be chained: `input:not([disabled]):not([readonly])`.",
    codeExample: "const secondaryButtons = document.querySelectorAll('button:not(.btn-primary)');\nsecondaryButtons.forEach(btn => btn.classList.add('outline'));",
    interviewTips: ["Mention that modern `:not()` supports comma-separated selectors: `:not(.a, .b)`."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Selector Performance",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "Why is getElementById() faster than querySelector('#id') in browser performance benchmarks?",
    shortAnswer: "`getElementById()` executes directly via the browser's internal ID hash map, whereas `querySelector()` must first parse and compile the CSS selector expression before performing the lookup.",
    detailedExplanation: "- **CSS Parsing Overhead**: `querySelector` tokenizes the string and compiles a selector state machine.\n- **Direct Map Access**: `getElementById` skips CSS parsing and accesses the document's internal hash table.\n- **Scale**: In microbenchmarks, `getElementById` can be 2x to 5x faster, though rarely noticeable in small apps.",
    codeExample: "// getElementById accesses hash table directly:\nconst el1 = document.getElementById('main-nav');\n\n// querySelector compiles CSS selector string first:\nconst el2 = document.querySelector('#main-nav');",
    interviewTips: ["Explain that CSS selector tokenization and parsing overhead is the root cause of the speed difference."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Live Collection Hazard",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "Why can accessing .length on a live HTMLCollection inside a loop condition cause severe performance degradation?",
    shortAnswer: "Evaluating `.length` on a live `HTMLCollection` forces the browser engine to re-query and re-verify the DOM tree on every iteration, turning an O(n) loop into an O(n^2) operation.",
    detailedExplanation: "- **Live Re-evaluation**: Live collections dynamically reflect DOM state; accessing `.length` forces a DOM scan if mutations occurred.\n- **Cache Length**: Always cache the length in a variable (`const len = collection.length`) before iterating.\n- **Convert to Array**: Converting to a static array (`Array.from(collection)`) eliminates repeated DOM queries.",
    codeExample: "const items = document.getElementsByClassName('item');\n// Bad: checks live length every iteration\n// for (let i = 0; i < items.length; i++) { ... }\n\n// Good: cache length or convert to static array\nconst list = Array.from(items);\nfor (let i = 0; i < list.length; i++) { /* Fast */ }",
    interviewTips: ["Highlight caching `.length` or converting live collections to static arrays to avoid repeated DOM re-evaluations."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: ":scope Pseudo-class",
    difficulty: "DIFFICULT",
    questionType: "CONCEPTUAL",
    question: "What is the :scope pseudo-class and how does it prevent querySelector from searching outside the contextual root?",
    shortAnswer: "`:scope` represents the element on which `querySelector` was called, allowing you to explicitly restrict selector matching to direct children without escaping the contextual element.",
    detailedExplanation: "- **Context Leak Gotcha**: In `container.querySelectorAll('div span')`, the selector engine evaluated from the document root, meaning `container.querySelectorAll('.outer span')` could match if `.outer` was an ancestor of `container`!\n- **`:scope` Anchor**: Using `container.querySelectorAll(':scope > span')` explicitly anchors the query to `container`.\n- **Direct Children**: Eliminates ambiguity when matching immediate descendants.",
    codeExample: "const card = document.querySelector('.card');\nconst directP = card.querySelectorAll(':scope > p');",
    interviewTips: ["Explain that `:scope > selector` is the standard way to query immediate children of an element."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Shadow Root Selection",
    difficulty: "DIFFICULT",
    questionType: "CONCEPTUAL",
    question: "How do you query elements inside an open Shadow DOM root from the main document script?",
    shortAnswer: "First query the shadow host element, access its `shadowRoot` property, and call `shadowRoot.querySelector(selector)`.",
    detailedExplanation: "- **Encapsulation Boundary**: `document.querySelector()` cannot penetrate into a Shadow Root.\n- **Open Mode**: If created with `mode: 'open'`, the host exposes `element.shadowRoot`.\n- **Closed Mode**: If created with `mode: 'closed'`, `element.shadowRoot` returns `null` and internal nodes cannot be accessed from outside.",
    codeExample: "const host = document.querySelector('my-custom-element');\nif (host.shadowRoot) {\n  const innerBtn = host.shadowRoot.querySelector('button.submit');\n  console.log('Found shadow button:', innerBtn);\n}",
    interviewTips: ["Differentiate open mode (`element.shadowRoot` accessible) from closed mode (`element.shadowRoot === null`)."]
  },
  {
    topic: "Element Selection & Collections",
    subtopic: "Document Tree Order Sorting",
    difficulty: "DIFFICULT",
    questionType: "CODE",
    question: "Given an arbitrary array of DOM elements, how do you sort them into their natural document tree order?",
    shortAnswer: "Sort the array using `a.compareDocumentPosition(b)` and checking the `Node.DOCUMENT_POSITION_FOLLOWING` bit.",
    detailedExplanation: "- **Tree Ordering**: Querying multiple elements via separate calls may produce an unsorted array.\n- **`compareDocumentPosition`**: Returns `Node.DOCUMENT_POSITION_FOLLOWING` (4) if `b` follows `a` in document order.\n- **Sort Comparator**: `elements.sort((a, b) => (a.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1))`.",
    codeExample: "function sortInDocumentOrder(elements) {\n  return elements.sort((a, b) => {\n    if (a === b) return 0;\n    const position = a.compareDocumentPosition(b);\n    return position & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1;\n  });\n}",
    interviewTips: ["Demonstrate how `compareDocumentPosition` solves the document order sorting challenge cleanly."]
  },

  // --- DOM Traversal & Navigation (71 - 100) ---
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "parentElement vs parentNode",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between parentElement and parentNode in the DOM?",
    shortAnswer: "`parentElement` returns the parent node only if it is an Element (type 1), returning `null` on the `<html>` root, whereas `parentNode` returns any parent node including the `Document` node.",
    detailedExplanation: "- **`document.documentElement.parentElement`**: Returns `null` because the parent of `<html>` is `document` (a Document node, not an Element).\n- **`document.documentElement.parentNode`**: Returns `document`.\n- **Everyday Elements**: For standard nested elements like `<div><p></p></div>`, both return the exact same parent `Element`.",
    codeExample: "const htmlEl = document.documentElement;\nconsole.log(htmlEl.parentNode === document); // true\nconsole.log(htmlEl.parentElement);           // null",
    interviewTips: ["This is a classic distinction test: `<html>` has a `parentNode` (document), but its `parentElement` is `null`."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "children vs childNodes",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between element.children and element.childNodes?",
    shortAnswer: "`element.children` returns an `HTMLCollection` containing only element nodes, while `element.childNodes` returns a `NodeList` containing all nodes including text and comments.",
    detailedExplanation: "- **`children`**: Live `HTMLCollection` of Element nodes (nodeType 1) only.\n- **`childNodes`**: Live `NodeList` of all child nodes (elements, whitespace text nodes, comments).\n- **Practical Use**: Use `children` when manipulating layout elements; use `childNodes` when parsing text content.",
    codeExample: "const div = document.createElement('div');\ndiv.innerHTML = 'Hello <p>Paragraph</p> <!-- note -->';\nconsole.log(div.children.length);   // 1 (<p> only)\nconsole.log(div.childNodes.length); // 3 (text, <p>, comment)",
    interviewTips: ["Use `children` when you only care about HTML tags; use `childNodes` when inspecting raw text or comments."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "firstElementChild vs firstChild",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between element.firstChild and element.firstElementChild?",
    shortAnswer: "`firstChild` returns the first child Node of any type (often a whitespace text node), while `firstElementChild` returns the first child Element tag.",
    detailedExplanation: "- **`firstChild`**: Evaluates to the first node in `childNodes`. In HTML with indentation, this is usually a `TextNode` containing newline characters.\n- **`firstElementChild`**: Evaluates to the first node in `children`, skipping all whitespace and comments.\n- **Best Practice**: In modern UI development, `firstElementChild` is almost always what developers intend to target.",
    codeExample: "<!-- HTML: <div>\n  <p>First</p>\n</div> -->\nconst div = document.querySelector('div');\nconsole.log(div.firstChild.nodeName);        // '#text' (whitespace)\nconsole.log(div.firstElementChild.nodeName); // 'P'",
    interviewTips: ["Highlight the whitespace gotcha: `firstChild` often returns `#text` due to HTML formatting."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "lastElementChild vs lastChild",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between element.lastChild and element.lastElementChild?",
    shortAnswer: "`lastChild` returns the last child Node of any type (often trailing whitespace), while `lastElementChild` returns the last child Element node.",
    detailedExplanation: "- **`lastChild`**: Returns the last entry in `childNodes`.\n- **`lastElementChild`**: Returns the last entry in `children`.\n- **Null Returns**: Both return `null` if the element has no children.",
    codeExample: "const list = document.querySelector('ul');\nconst lastLi = list.lastElementChild;\nconsole.log('Last item text:', lastLi.textContent);",
    interviewTips: ["Always prefer `lastElementChild` over `lastChild` when querying HTML tag elements."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "nextElementSibling vs nextSibling",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What is the difference between nextSibling and nextElementSibling in the DOM?",
    shortAnswer: "`nextSibling` returns the immediate next sibling Node of any type (often whitespace text), while `nextElementSibling` returns the next sibling Element tag.",
    detailedExplanation: "- **`nextSibling`**: Can be text, comment, or element. Returns `null` if this is the last child node.\n- **`nextElementSibling`**: Skips text and comments to find the next Element. Returns `null` if no subsequent element sibling exists.\n- **Symmetry**: `previousSibling` vs `previousElementSibling` operate symmetrically in the preceding direction.",
    codeExample: "const h1 = document.querySelector('h1');\nconst nextTag = h1.nextElementSibling;\nconsole.log('Next tag after H1:', nextTag ? nextTag.tagName : 'None');",
    interviewTips: ["State that `nextElementSibling` ignores whitespace text nodes, making UI sibling navigation reliable."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "previousElementSibling",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How do you navigate to the preceding sibling element of a node?",
    shortAnswer: "Access `element.previousElementSibling`, which returns the previous sibling Element, or `null` if the element is the first child element of its parent.",
    detailedExplanation: "- **Element-Only**: Ignores comments and whitespace text nodes between tags.\n- **Boundary**: Returns `null` if called on the first child element of a container.\n- **Accordion Navigation**: Useful when a clicked content panel needs to find its accordion header trigger.",
    codeExample: "const panel = document.querySelector('.panel-content');\nconst header = panel.previousElementSibling;\nif (header) header.classList.add('expanded');",
    interviewTips: ["Contrast `previousElementSibling` (element only) with `previousSibling` (includes text/comments)."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "childElementCount Property",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does element.childElementCount return?",
    shortAnswer: "`element.childElementCount` returns the number of child Element nodes inside the element, exactly equivalent to `element.children.length`.",
    detailedExplanation: "- **Fast Counter**: Provides a fast integer count without allocating a collection.\n- **Elements Only**: Excludes text nodes, comments, and whitespace.\n- **Equivalent**: Equal to `element.children.length`.",
    codeExample: "const list = document.querySelector('ul.todo-list');\nif (list.childElementCount === 0) {\n  console.log('No tasks remaining!');\n}",
    interviewTips: ["Mention that `childElementCount` is a clean readability shortcut for `children.length`."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "closest Traversal",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How does element.closest() traverse the DOM tree?",
    shortAnswer: "`element.closest(selector)` inspects the element itself first, then traverses upwards through its ancestors, returning the first matching element or `null`.",
    detailedExplanation: "- **Upward Traversal**: Moves up from target towards `document.documentElement`.\n- **Self-Inclusive**: If the element itself matches the selector, traversal terminates immediately and returns the element.\n- **Event Delegation**: Essential for identifying the parent row or card when an icon inside a button is clicked.",
    codeExample: "document.querySelector('table').addEventListener('click', (e) => {\n  const row = e.target.closest('tr');\n  if (row) console.log('Clicked row ID:', row.dataset.id);\n});",
    interviewTips: ["Explain that `closest` starts with self before moving to parents."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "matches Check",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "What does element.matches(selector) do during DOM traversal?",
    shortAnswer: "`element.matches(selector)` tests if the element matches the provided CSS selector string, returning `true` or `false` without navigating the tree.",
    detailedExplanation: "- **Boolean Verification**: Validates whether an element matches a selector.\n- **No Traversal**: Does not navigate parents or children; inspects the single element in isolation.\n- **Event Filtering**: Used in event delegation: `if (e.target.matches('.delete-btn')) { ... }`.",
    codeExample: "const el = document.querySelector('#btn');\nif (el.matches('.primary:not(:disabled)')) {\n  console.log('Button is active primary button.');\n}",
    interviewTips: ["Highlight `matches()` as the standard condition check inside event delegation handlers."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "Checking Descendants",
    difficulty: "EASY",
    questionType: "CONCEPTUAL",
    question: "How do you check if an element is contained within another element in the DOM?",
    shortAnswer: "Call `container.contains(targetNode)`, which returns `true` if `targetNode` is a descendant of `container` or is `container` itself.",
    detailedExplanation: "- **Descendant Check**: Evaluates children, grandchildren, and any arbitrary depth.\n- **Self-Match**: `container.contains(container)` evaluates to `true`.\n- **Outside Click Detection**: Fundamental for closing modals or dropdown menus when a click occurs outside their container.",
    codeExample: "const modal = document.querySelector('.modal-box');\ndocument.addEventListener('click', (e) => {\n  if (!modal.contains(e.target)) {\n    modal.classList.add('hidden'); // Clicked outside!\n  }\n});",
    interviewTips: ["Remember that `container.contains(container)` is `true`."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "Looping Siblings",
    difficulty: "INTERMEDIATE",
    questionType: "CODE",
    question: "How do you iterate through all sibling elements of a given element in the DOM?",
    shortAnswer: "Access `element.parentElement.children` and filter out the element itself, or navigate iteratively using `nextElementSibling`.",
    detailedExplanation: "- **Approach 1 (Parent Children)**: `[...element.parentElement.children].filter(el => el !== element)`.\n- **Approach 2 (Iterative)**: Start at `element.parentElement.firstElementChild` and walk `nextElementSibling` until null.\n- **Tab Panels**: Frequently used to deactivate sibling tabs when an active tab is selected.",
    codeExample: "function getSiblings(element) {\n  return [...element.parentElement.children].filter(el => el !== element);\n}\n\n// Deactivating sibling buttons:\nconst activeBtn = document.querySelector('.btn.active');\ngetSiblings(activeBtn).forEach(btn => btn.classList.remove('active'));",
    interviewTips: ["Explain the array filter approach vs the `nextElementSibling` loop approach."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "Depth-First DOM Traversal",
    difficulty: "INTERMEDIATE",
    questionType: "CODE",
    question: "How do you implement a recursive depth-first traversal of a DOM subtree?",
    shortAnswer: "Process the root node, then recursively invoke the traversal function on each element in `element.children`.",
    detailedExplanation: "- **Pre-Order Traversal**: Process the current element before visiting its children.\n- **Recursion**: Loop over `element.children` and recurse.\n- **Stack Depth**: In typical web documents, nesting depth rarely exceeds 30-40 levels, making recursion completely safe.",
    codeExample: "function traverseDOM(node, callback) {\n  callback(node);\n  for (const child of node.children) {\n    traverseDOM(child, callback);\n  }\n}\n\n// Logging all tag names in subtree:\ntraverseDOM(document.body, el => console.log(el.tagName));",
    interviewTips: ["Clarify that using `children` filters to element nodes, whereas `childNodes` traverses text/comments."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "TreeWalker Filtering",
    difficulty: "INTERMEDIATE",
    questionType: "CODE",
    question: "How do you use a custom filter function with document.createTreeWalker()?",
    shortAnswer: "Pass a filter object with an `acceptNode(node)` method returning `NodeFilter.FILTER_ACCEPT`, `NodeFilter.FILTER_REJECT`, or `NodeFilter.FILTER_SKIP`.",
    detailedExplanation: "- **`FILTER_ACCEPT`**: Includes the node and visits its children.\n- **`FILTER_REJECT`**: Rejects the node AND skips its entire child subtree.\n- **`FILTER_SKIP`**: Skips this specific node, but continues inspecting its children.\n- **Performance**: High-speed native C++ traversal engine.",
    codeExample: "const walker = document.createTreeWalker(\n  document.body,\n  NodeFilter.SHOW_ELEMENT,\n  {\n    acceptNode(node) {\n      return node.classList.contains('sensitive') \n        ? NodeFilter.FILTER_REJECT \n        : NodeFilter.FILTER_ACCEPT;\n    }\n  }\n);",
    interviewTips: ["Contrast `FILTER_REJECT` (skips node and its subtree) with `FILTER_SKIP` (skips node but traverses its children)."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "Finding Common Ancestor",
    difficulty: "INTERMEDIATE",
    questionType: "CODE",
    question: "How do you find the lowest common ancestor of two DOM nodes?",
    shortAnswer: "Use `a.contains(b)` while walking up `a = a.parentElement`, or use a `Range` object with `range.commonAncestorContainer`.",
    detailedExplanation: "- **Approach 1 (Range Object)**: Create a Range (`document.createRange()`), set start and end points, and read `range.commonAncestorContainer`.\n- **Approach 2 (Traversal Loop)**: Traverse up from node `a` until `ancestor.contains(b)` evaluates to `true`.\n- **Performance**: Range API is native and executes in C++ speed.",
    codeExample: "function getLowestCommonAncestor(nodeA, nodeB) {\n  const range = document.createRange();\n  range.setStart(nodeA, 0);\n  range.setEnd(nodeB, 0);\n  return range.commonAncestorContainer;\n}",
    interviewTips: ["Highlight the `Range.commonAncestorContainer` trick as an elegant one-line solution."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "Breadth-First DOM Traversal",
    difficulty: "INTERMEDIATE",
    questionType: "CODE",
    question: "How do you implement a breadth-first search (BFS) level-order traversal of the DOM tree?",
    shortAnswer: "Use a queue (array with `shift()` and `push()`), enqueuing the root node and iteratively processing nodes level-by-level.",
    detailedExplanation: "- **Queue Data Structure**: First-In-First-Out (FIFO) queue guarantees visiting elements by depth level.\n- **Algorithm**: Enqueue root, while queue is not empty: dequeue current node, process it, enqueue all its `children`.\n- **Use Cases**: Finding the shallowest element matching a criteria.",
    codeExample: "function breadthFirstTraversal(root, callback) {\n  const queue = [root];\n  while (queue.length > 0) {\n    const current = queue.shift();\n    callback(current);\n    for (const child of current.children) {\n      queue.push(child);\n    }\n  }\n}",
    interviewTips: ["Explain that BFS visits nodes level by level using a queue, unlike DFS which dives down branches via recursion."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "compareDocumentPosition",
    difficulty: "INTERMEDIATE",
    questionType: "CONCEPTUAL",
    question: "How do you determine if node A appears before node B in the document using compareDocumentPosition?",
    shortAnswer: "Check `nodeA.compareDocumentPosition(nodeB) & Node.DOCUMENT_POSITION_FOLLOWING`, which evaluates to truthy if `nodeB` follows `nodeA`.",
    detailedExplanation: "- **Bitmask Result**: `compareDocumentPosition` returns a bitmask integer.\n- **`Node.DOCUMENT_POSITION_PRECEDING` (2)**: Node B precedes Node A.\n- **`Node.DOCUMENT_POSITION_FOLLOWING` (4)**: Node B follows Node A.\n- **Bitwise AND (`&`)**: Essential because multiple position flags can be active simultaneously (e.g., following AND contained).",
    codeExample: "const a = document.querySelector('#intro');\nconst b = document.querySelector('#conclusion');\n\nif (a.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING) {\n  console.log('Conclusion appears after Intro in the document.');\n}",
    interviewTips: ["Emphasize using bitwise AND (`&`) rather than equality (`===`) due to bitmask flags."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "Circular References in Traversal",
    difficulty: "DIFFICULT",
    questionType: "CONCEPTUAL",
    question: "Can standard DOM tree traversal encounter circular reference loops in the DOM hierarchy?",
    shortAnswer: "No, the standard DOM hierarchy is strictly an acyclic tree; an element cannot be an ancestor of itself, preventing circular loops during tree traversal.",
    detailedExplanation: "- **Tree Invariant**: Web standards strictly enforce that a node can only have one parent at any time.\n- **DOMException Error**: Attempting to append an element to one of its own descendants throws `HierarchyRequestError`.\n- **Graph Contrast**: While JavaScript object references can be circular, the DOM parent-child hierarchy is always a directed acyclic graph (tree).",
    codeExample: "const parent = document.createElement('div');\nconst child = document.createElement('div');\nparent.appendChild(child);\n\ntry {\n  // Attempting to make parent a child of its own child:\n  child.appendChild(parent);\n} catch (err) {\n  console.log(err.name); // 'HierarchyRequestError'\n}",
    interviewTips: ["Explain that `HierarchyRequestError` is thrown by the browser if you attempt to create a circular DOM relationship."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "ownerDocument Property",
    difficulty: "DIFFICULT",
    questionType: "CONCEPTUAL",
    question: "What is node.ownerDocument and when does it return null?",
    shortAnswer: "`node.ownerDocument` returns the `Document` object associated with the node, and returns `null` only when called on the `document` node itself.",
    detailedExplanation: "- **Ownership**: Every element, text node, and comment belongs to a specific Document object.\n- **Iframes**: Elements created inside an iframe have that iframe's `contentDocument` as their `ownerDocument`.\n- **Cross-Document Operations**: Elements cannot be inserted into another document without first calling `document.importNode()` or `document.adoptNode()`.",
    codeExample: "const div = document.createElement('div');\nconsole.log(div.ownerDocument === document); // true\nconsole.log(document.ownerDocument);        // null (Document has no owner)",
    interviewTips: ["Remember: `document.ownerDocument` is `null` because document is the top-level owner."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "Shadow Root Retargeting in Traversal",
    difficulty: "DIFFICULT",
    questionType: "CONCEPTUAL",
    question: "How does DOM tree traversal behave when crossing Shadow DOM boundaries?",
    shortAnswer: "Standard traversal methods like `parentElement` and `querySelector` cannot cross Shadow Root boundaries, stopping at the shadow boundary unless navigated via `shadowRoot.host` or `composedPath()`.",
    detailedExplanation: "- **Encapsulation Boundary**: `parentElement` on a top-level shadow child returns `null` or the shadow root, not the outer host.\n- **Escape to Host**: Access the hosting element via `shadowRoot.host`.\n- **Event Path Traversal**: `event.composedPath()` provides the full un-retargeted path across all shadow boundaries.",
    codeExample: "const shadowHost = document.querySelector('custom-card');\nconst innerBtn = shadowHost.shadowRoot.querySelector('button');\n\nconsole.log(innerBtn.parentElement); // Element inside shadow root\nconsole.log(innerBtn.getRootNode().host === shadowHost); // true",
    interviewTips: ["Mention `getRootNode().host` as the standard way to traverse from inside shadow DOM back to the outer host."]
  },
  {
    topic: "DOM Traversal & Navigation",
    subtopic: "Live Selection vs Traversal Performance",
    difficulty: "DIFFICULT",
    questionType: "CONCEPTUAL",
    question: "In performance-critical scenarios, why is traversing from a cached parent (e.g. parent.firstElementChild) faster than re-querying with querySelector?",
    shortAnswer: "Direct traversal navigates native C++ pointer references directly, completely skipping CSS selector string parsing, tokenization, and subtree scanning.",
    detailedExplanation: "- **Pointer Traversal**: Properties like `nextElementSibling` and `parentElement` are direct memory pointer reads in C++.\n- **CSS Engine Bypass**: Avoids invoking the CSS selector engine, rule matching, and DOM tree searches.\n- **High Frequency**: In 60 FPS animation loops or canvas interaction handlers, direct pointer traversal prevents frame drops.",
    codeExample: "// Fast pointer traversal:\nconst nextItem = currentElement.nextElementSibling;\n\n// Slower CSS search:\n// const nextItem = currentElement.parentElement.querySelector(':scope > .item:nth-child(2)');",
    interviewTips: ["Highlight direct memory pointer navigation vs selector engine compilation."]
  }
];

module.exports = questions;
